services:
  watcher:
    build: .
    container_name: system_watcher
    restart: always
    volumes:
      - .:/app
      - ./logs:/app/logs
    env_file:
      - .env
    networks:
      - observability

  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.template:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - watcher
    networks:
      - observability

networks:
  observability:
    driver: bridge
